export default {
  ADD_POST: 'ADD_POST',
  DELETE_POST: 'DELETE_POST',
  UPDATE_POST: 'UPDATE_POST',

  SET_INPUT_TITLE: 'SET_INPUT_TITLE',
  SET_INPUT_CONTENT: 'SET_INPUT_CONTENT',
  RESET_INPUT: 'RESET_INPUT',
};
